### ISSUE TITLE
Already have json file

### ISSUE THREAD

**Issue by Doliliserrr** [taseikyo/backup-utils#5]
I have a json file which downloaded from bilibili already ! How to convert it to srt ? Help please  !! Thanks

**Comment by taseikyo** [comment]
> I have a json file which downloaded from bilibili already ! How to convert it to srt ? Help please !! Thanks

The [convert_to_srt(srt_id: str, subtitles: list)](https://github.com/taseikyo/backup-utils/blob/master/Python/008_download_and_convert_b23_subtitle.py#L40) function can complete the conversion.
The `srt_id` is the id of the generated srt file you need to specify, and the `subtitles` is the content of the json file you downloaded.
